# Generated by Django 4.0 on 2022-10-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysubscribers',
            name='subscriber_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Подписчик'),
        ),
    ]
